[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./out"}]

[rpc_endpoints]
conflux = "${CONFLUX_RPC}"

[etherscan]
conflux = { key = "${CONFLUXSCAN_API_KEY}", chain = 71, url = "${VERIFIER_URL}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
